### ISSUE TITLE
currentUser has nil fields directly after  [SmoochHelpKit initWithSettings:settings];

### ISSUE THREAD

**Issue by fatuhoku** [smooch/smooch-ios#64] opened 2015-12-01 12:15 UTC
I've logged in and set various properties on `currentUser`. I want to know whether these properties can are cached between restarts — because I'm having issues accessing those fields after app launch.

The docs say:

```objc
/**
 *  @abstract The object representing the current user.
 *  @discussion Returns nil if +initWithSettings: has not been called yet.
 *  @see Smooch
 */
```

But even if I do

```objc

    // In `-application:didFinishLaunchingWithOptions:`

    [SmoochHelpKit initWithSettings:settings];
    SKTUser *user = [SKTUser currentUser];

    NSString *sktUserStringDescription = user == nil
            ? @"NONE"
            : [NSString stringWithFormat:@"SKTUser(email: %@, firstName: %@, lastName: %@, signedUpAt: %@)"
                    , user.email, user.firstName, user.lastName, user.signedUpAt];
    NSLog(@"Current Smooch User is: %@", sktUserStringDescription);

    // prints "Current Smooch User is: SKTUser(email: (null), firstName: (null), lastName: (null), signedUpAt: (null))"
```

I use `lldb` to inspect the value of `[SKTUser currentUser]` later in the application lifecycle and sure enough the fields are actually populated.

```objc
(lldb) p [(SKTUser *)[SKTUser currentUser] firstName]
(NSTaggedPointerString *) $0 = 0xa000000747365744 @"test"
(lldb) p [(SKTUser *)[SKTUser currentUser] lastName]
(NSString *) $1 = nil
(lldb) p [(SKTUser *)[SKTUser currentUser] email]
(__NSCFString *) $2 = 0x00007f8ef4441fd0 @"test@example.com"
```

**Comment by fatuhoku** [comment] 2015-12-01 12:28
My current workaround is to insert a delay. It takes between 0.6 seconds and 1.0 seconds before the currentUser's fields are populated. I suspect there's actually network call going on here; I expected it to have been cached locally actually.

```objc
    // FIXME Smooch takes a lil' while to fetch the currentUser
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self printCurrentSmoochUser];
    });
```

**Comment by mspensieri** [comment] 2015-12-01 13:39
You're correct that these values are not cached locally, but that's actually by design. The `SKTUser` class is not intended to be used as your main data store, it's supposed to mirror the values you have set persistently somewhere else. This is why we expose `addProperties:` but not `getProperty:`. The fact that you can even read `email`, `firstName`, etc... at all after setting them is a side-effect of the implementation (i.e. we chose to use properties rather than just setter methods).

What is your use case for reading back the values of these properties?

**Comment by fatuhoku** [comment] 2015-12-01 15:14
Yep I guessed that was the case. @mspensieri my use case isn't a real one — as a developer it's just helpful to see what the Smooch user has been identified as when my application launches, so that I have some confidence that the user is being identified correctly. That was all really.

**Comment by mspensieri** [comment] 2015-12-01 19:13
Ah ok, I'l close this issue then as there's nothing to do

**Closed by mspensieri** 2015-12-01 19:13 UTC
