### ISSUE TITLE
Crash in [SKTSRWebSocket stream:handleEvent:]

### ISSUE THREAD

**Issue by aoverholtzer** [smooch/smooch-ios#96] opened 2016-04-18 21:12 UTC
I've gotten a couple of crash reports for a EXC_BAD_ACCESS crash in [SKTSRWebSocket stream:handleEvent:]. More details here: http://crashes.to/s/32f46131d78

I am using the latest version of Smooch (4.1.2).

**Comment by mspensieri** [comment] 2016-04-19 13:04
Thanks for the report. From the link you provided it shows there is only 1 instance of the crash, can you give a rough estimate of what this translates to in terms of % of impacted users? Did you see this crash in production, or during testing?

**Comment by aoverholtzer** [comment] 2016-04-19 23:33
The Smooch-integrated version of our app is still in development, so we only have a handful (<10) active users. We're planning to push it to our beta testers (~100) next week and to production by mid-May. Thanks for the help!

There is a similar crash report for an older build of our app (same version of Smooch): http://crashes.to/s/cfa641289c0

**Comment by mspensieri** [comment] 2016-04-22 12:29
Thanks for the info. I was able to reproduce on my side, seems to be an intermittent crash when the websocket connection to the server is interrupted for some reason. I suspect some sort of timing issue, since it doesn't reproduce every time. Will investigate further.

**Comment by jugarrit** [comment] 2016-05-13 16:01
Hey @aoverholtzer,

I started to take a look at this issue today, but we can't seem to figure out how to reproduce it and so it's quite difficult to debug. Would you happen to know a reliable way to cause this?

**Comment by aoverholtzer** [comment] 2016-05-13 16:33
Hi @jugarrit,
Unfortunately, I have only seen this crash in my Crashlytics logs and haven’t been able to reproduce. It sounds like @mspensieri was able to reproduce it, so maybe he can help.

**Comment by mspensieri** [comment] 2016-05-13 18:28
I reproduced it by accident 5-6 times in a row while developing something else, but haven't been able to reproduce it since then :(

I couldn't figure out any reliable repro steps

**Comment by aoverholtzer** [comment] 2016-05-13 18:40
I haven’t seen the crash since April 30, and we’ve only increased our number of beta testers since then. Maybe you guys fixed/updated something else that fixed this crash?

**Comment by mspensieri** [comment] 2016-05-13 18:45
Hmm could be. We made a small change in v4.2.0 that affected this area, maybe it fixed the problem? I'll close this issue for now, please reopen if the crash returns

**Closed by mspensieri** 2016-05-13 18:45 UTC
