### ISSUE TITLE
Search bar disappears when Messages and an article are tapped

### ISSUE THREAD

**Issue by gemmakbarlow** [smooch/smooch-ios#49] opened 2015-06-17 01:26 UTC
## Summary

This was originally raised by internal testers on my current project, but I've since been able to reproduce it with the SupportKit Demo App.

Please note that the issue is very difficult to reproduce on the Simulator, because it requires multiple taps; the app will need to be installed on device. 

----

### Frequency
Every Time

### Action
1. Install and open application
2. Tap the top left Account icon
3. Tap Help
4. Search any term e.g. "Test"
5. Tap the article and the Messages button at the same time
6. Tap Done on the messages prompt

### Expected Result
The user should land on the article page with no UI issues

### Actual Result
The top search bar disappears and is replaced by a grey top banner

### Additional Information
iPhone 6 iOS 8.3
AT&T LTE

Can be consistently reproduced.

----

![img_1600](https://cloud.githubusercontent.com/assets/337963/8198007/55ac0b8e-146e-11e5-837b-372b53f1f391.PNG)

**Comment by mspensieri** [comment] 2015-11-25 19:40
Closing this issue since it no longer applies to this project. If it still reproduces with the latest version, you can open an issue (or pull request) on the [HelpKit](https://github.com/smooch/smooch-helpkit-ios) repo :)

**Closed by mspensieri** 2015-11-25 19:40 UTC
Labels: bug
