### ISSUE TITLE
Conversation controller allow to send messages only once

### ISSUE THREAD

**Issue by IljaKosynkin** [smooch/smooch-ios#179] opened 2017-11-07 00:01 UTC
**Environment:**

- xCode 9.0
- Swift 4
- iOS 10.3.3
- Integrated with Slack

**Integration steps:**
I integrated Smooch SDK exactly as per doc, i.e.

- Added Smooch.initWith(settings, completion) call (called in AppDelegate if user is logged in, otherwise - after user login)
- Calling chat controller via Smooch.show()

**Issue description:**
It's really weird: text field in chat works only for one session for me. Scenario looks like that:

1. I open up chat for the first time. I can freely communicate, send photos, receive messages and so on
2. I close chat
3. I open chat again and text field is not responding to clicks. Basically, it feels like user interactions are disabled. Also, really weird part is: I can send photos, photo button is working normally. Just clicking on text field doesn't bring up keyboard, so I can't type anything

Issue persists, unless I actually reinstall application. Then I can use chat again for once and next trials will fail.
Any help?
If I missed something, please tell me, I will provide additional information.
Also, a bit of a side question: is there a way to reinitialize Smooch chat session when user enters chat again? I actually don't want to keep history of previous conversations.

**Comment by mspensieri** [comment] 2017-11-07 13:31
Hi @IljaKosynkin, thanks for the report.

> If I missed something, please tell me, I will provide additional information.

If you could provide a sample project that reproduces this issue, that would be great. I am not able to reproduce this in my own test application.

> Also, a bit of a side question: is there a way to reinitialize Smooch chat session when user enters chat again? I actually don't want to keep history of previous conversations.

You clear the history of a conversation by calling the [Delete Messages API](https://docs.smooch.io/rest/#delete-messages) from your backend when you want to clear the history, but by default this is not something you can do using just the SDK at the moment.

**Comment by IljaKosynkin** [comment] 2017-11-07 15:40
Hello, @mspensieri.
Unfortunately, I don't think I actually can provide such project. I can't disclose source code of my current project (and it's quite big project, 61K lines and counting) and simple project without anything seems to be working fine.
What can cause such behaviour? 
I also took a UI snapshot, and I seems that field has user interactions turned off.
What can theoretically cause such blocking? Is there some precondition that needs to be fulfilled, beside Smooch.initWith call prior to chat?

**Comment by mspensieri** [comment] 2017-11-08 13:27
The chat input is disabled while the table view is loading its content. You should see a spinner in place of the message bubbles while this is happening. Aside from that, there is no other condition that would cause the input to be disabled.

The only thing I can think is that somehow the table view is not correctly loading its content, or is failing to notify the containing view controller when that happens. Without more information though all I can do is guess at the problem. 

> simple project without anything seems to be working fine.

If the issue doesn't reproduce in an empty project, then the SDK must be conflicting with something else that is happening in your app. Maybe some additional context will help

1. How are you presenting the Smooch view controller? Is it via `[Smooch show]`, or `[Smooch newConversationViewController]`? In a navigation controller? Modally?
2. Can you give a brief summary of the view controller hierarchy at the time the conversation is displayed?
3. Is your app including any external dependencies that are changing the behaviour of table views in your app, or swizzling any view controller lifecycle methods?

**Comment by IljaKosynkin** [comment] 2017-11-08 14:25
@mspensieri 
Content is actually loading fine. How exactly notifying of view controller works? Is it a delegate or NotificationCenter? If it is NotificationCenter, maybe some kind of key is colliding with our code?
Yep, I guess that there is some conflict. 
As for your questions:
1. Tried both, each approach had exactly the same problem.

2. Sure. UI snapshot shows only SKTConversationViewController. Whole hierarchy is following: UINavigationController with UITabBarController inside, UINavigationController with root UIViewController presented modally on top of that and SKTConversationViewController over all of this.

3. I searched thru codebase for UITableView, UIViewController and _set strings to see in something weird is being applied to them and haven't found anything suspicious. However in out code we have following overrides in UIViewController extension:
    open override var canBecomeFirstResponder: Bool { return true }
    open override func motionEnded(_ motion: UIEventSubtype, with event: UIEvent?) { /* code */ }
I tried to comment it out, but it doesn't seems like ti helped.

**Comment by mspensieri** [comment] 2017-11-08 20:37
It's notified via the `UITableViewDelegate` protocol, specifically when `tableView:willDisplayCell:forRowAtIndexPath` is called for the first cell in the table view, so it wouldn't be a notification center key conflict.

> Content is actually loading fine.

So the message history is displayed, but the input is still disabled? If you reset your simulator and launch the conversation screen in empty state, are you able to hide the keyboard and open it again? User interaction is only disabled in the case where there are messages?

**Comment by IljaKosynkin** [comment] 2017-11-08 22:54
@mspensieri 
Is there some if or guard condition on this notification in tableView:willDisplayCell:forRowAtIndexPath? Because content is definitely there, so delegate method should be executed.
I actually tested primarily on my device. I tried reinstalling the app multiple times.
As for content I just tried to close the screen without writing and sending anything and then opened it again - still the same result (fresh install). It seems like after first open of the controller, input is just getting blocked. I thought that there might be a leak, but there is no SKT controller in the memory, so I guess it's not the case. 
Do you persist some states in the UserDefaults? May be conflict is in here? We actually setting language in "AppleLanguages" UserDefaults key, can it be related (only one key that might be common I guess)?

**Comment by mspensieri** [comment] 2017-11-09 16:55
View controllers do not share state with one another, I can't think of any reason why it would work the first time and not the second, especially if there are no messages in both launches.

Since I am unable to reproduce this issue, and you say that the issue similarly does not reproduce in a sample project, it seems clear that this is some kind of conflict between our SDK and your app, though I'm not sure where that conflict could be. I'm going to close this issue, but please reopen if you come up with steps to reproduce, or a sample project that you can provide demonstrating the issue.

**Closed by mspensieri** 2017-11-09 16:55 UTC
